import pandas as pd

data = [
    {'Name': 'Vermeiren Princeps', 'Sponsor': 'N/A', 'Location': 'S2-D61 ', 'Pavilion': '5', 'Hall Number': 'Shk Saeed Hall 2', 'Country': 'Belgium', 'Company Type': 'Manufacturer'},
    {'Name': 'Vermuyten - Professional Dairy Products', 'Sponsor': 'N/A', 'Location': 'D2-26 ', 'Pavilion': '10', 'Hall Number': 'Hall 2', 'Country': 'Spain', 'Company Type': 'Manufacturer'},
    {'Name': 'Vertika', 'Sponsor': 'N/A', 'Location': 'R-270 ', 'Pavilion': '5', 'Hall Number': 'Shk Rashid Hall', 'Country': 'Syria', 'Company Type': 'Manufacturer'},
    {'Name': 'VESTEY FOODS INTERNATIONAL LTD', 'Sponsor': 'N/A', 'Location': 'F4-29 ', 'Pavilion': '10', 'Hall Number': 'Hall 4', 'Country': 'United Kingdom', 'Company Type': 'Importer/ Trader/ Wholesaler'},
    {'Name': 'VHUMANA, SA', 'Sponsor': 'N/A', 'Location': 'Z2-D75 ', 'Pavilion': '10', 'Hall Number': "Za'abeel Hall 2", 'Country': 'Portugal', 'Company Type': 'Importer/ Trader/ Wholesaler'},
    {'Name': 'Vibgyor Food Industries', 'Sponsor': 'N/A', 'Location': 'Z5-E15 ', 'Pavilion': '15', 'Hall Number': "Za'abeel Hall 5", 'Country': 'India', 'Company Type': 'Manufacturer'},
    {'Name': 'Vibra Food Trading LLC', 'Sponsor': 'N/A', 'Location': 'F3-26 ', 'Pavilion': '25', 'Hall Number': 'Hall 3', 'Country': 'Brazil', 'Company Type': 'N/A'},
    {'Name': 'Vicenzi S.p.A.', 'Sponsor': 'N/A', 'Location': 'S1-D25 ', 'Pavilion': '15', 'Hall Number': 'Shk Saeed Hall 1', 'Country': 'Italy', 'Company Type': 'Manufacturer'},
    {'Name': 'Vicky Foods - Dulcesol', 'Sponsor': 'N/A', 'Location': 'S1-K50 ', 'Pavilion': '15', 'Hall Number': 'Shk Saeed Hall 1', 'Country': 'Spain', 'Company Type': 'Manufacturer'},
    {'Name': 'Victoria Foods Pvt. Ltd. (Rajdhani Group)', 'Sponsor': 'N/A', 'Location': 'Z5-F10 ', 'Pavilion': '5', 'Hall Number': "Za'abeel Hall 5", 'Country': 'India', 'Company Type': 'N/A'},
    {'Name': 'Victoria Pulse Trading Corporation', 'Sponsor': 'N/A', 'Location': 'Z4-G6 ', 'Pavilion': 'N/A', 'Hall Number': "Za'abeel Hall 4", 'Country': 'Canada', 'Company Type': 'N/A'},
    {'Name': 'Vidrate', 'Sponsor': 'N/A', 'Location': 'S1-B44 ', 'Pavilion': 'N/A', 'Hall Number': 'Shk Saeed Hall 1', 'Country': 'United Kingdom', 'Company Type': 'N/A'},
    {'Name': 'Vidya Herbs Private Limited', 'Sponsor': 'N/A', 'Location': 'Z2-B82 ', 'Pavilion': '20', 'Hall Number': "Za'abeel Hall 2", 'Country': 'India', 'Company Type': 'Manufacturer'},
    {'Name': 'Vieira de Castro, SA', 'Sponsor': 'N/A', 'Location': 'S-L4 ', 'Pavilion': '10', 'Hall Number': 'Trade Centre Arena', 'Country': 'Portugal', 'Company Type': 'Manufacturer'},
    {'Name': 'Vietnam Dairy Products Jsc (Vinamilk)', 'Sponsor': 'N/A', 'Location': 'M-H57 ', 'Pavilion': '3', 'Hall Number': 'Shk Maktoum Hall', 'Country': 'Vietnam', 'Company Type': 'Manufacturer'},
    {'Name': 'Viet Nam Pepper and Spice Association', 'Sponsor': 'N/A', 'Location': 'ZP-B42 ', 'Pavilion': '25', 'Hall Number': "Za'abeel Plaza", 'Country': 'Vietnam', 'Company Type': 'N/A'},
    {'Name': 'Vikrma Impex Pvt. Ltd.', 'Sponsor': 'N/A', 'Location': 'ZL-A8 ', 'Pavilion': '10', 'Hall Number': "Za'abeel Hall 3", 'Country': 'India', 'Company Type': 'Manufacturer'},
    {'Name': 'Viktor and K Private Enterprise', 'Sponsor': 'N/A', 'Location': 'S2-D64 ', 'Pavilion': '5', 'Hall Number': 'Shk Saeed Hall 2', 'Country': 'Ukraine', 'Company Type': 'Manufacturer'},
    {'Name': 'VILACONIC', 'Sponsor': 'N/A', 'Location': 'ZP-B42 ', 'Pavilion': '0', 'Hall Number': "Za'abeel Plaza", 'Country': 'Vietnam', 'Company Type': 'Manufacturer'},
    {'Name': 'Vilgain', 'Sponsor': 'N/A', 'Location': 'S3-B50 ', 'Pavilion': '5', 'Hall Number': 'Shk Saeed Hall 3', 'Country': 'Czech Republic', 'Company Type': 'Manufacturer'},
    {'Name': '"VIL Group" LLC', 'Sponsor': 'N/A', 'Location': 'Z5-C11 ', 'Pavilion': 'N/A', 'Hall Number': "Za'abeel Hall 5", 'Country': 'Russian Federation', 'Company Type': 'Importer/ Trader/ Wholesaler'},
    {'Name': 'Vilkyskiy Pienine AB,Vilvi Group', 'Sponsor': 'N/A', 'Location': 'F2-20 ', 'Pavilion': '10', 'Hall Number': 'Hall 2', 'Country': 'Lithuania', 'Company Type': 'Manufacturer'},
    {'Name': 'Villa Germania Alimentos S.A', 'Sponsor': 'N/A', 'Location': 'E3-41 ', 'Pavilion': '10', 'Hall Number': 'Hall 3', 'Country': 'Brazil', 'Company Type': 'Manufacturer'},
    {'Name': 'Villares S.A.C.', 'Sponsor': 'N/A', 'Location': 'S-G11 ', 'Pavilion': 'N/A', 'Hall Number': 'Trade Centre Arena', 'Country': 'Argentina', 'Company Type': 'Manufacturer'},
    {'Name': 'VILUX', 'Sponsor': 'N/A', 'Location': 'S2-C59 ', 'Pavilion': '5', 'Hall Number': 'Shk Saeed Hall 2', 'Country': 'France', 'Company Type': 'Manufacturer'},
    {'Name': 'Vinapro Group JSC', 'Sponsor': 'N/A', 'Location': 'M-G46 ', 'Pavilion': 'N/A', 'Hall Number': 'Shk Maktoum Hall', 'Country': 'Vietnam', 'Company Type': 'Manufacturer'},
    {'Name': 'Vinh Hoan Corporation - VN', 'Sponsor': 'N/A', 'Location': 'MP-B27 ', 'Pavilion': '15', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'Vietnam', 'Company Type': 'Manufacturer'},
    {'Name': 'Vintage Coffee And Beverages Limited', 'Sponsor': 'N/A', 'Location': 'Z2-F69 ', 'Pavilion': 'N/A', 'Hall Number': "Za'abeel Hall 2", 'Country': 'India', 'Company Type': 'Manufacturer'},
    {'Name': 'Vintage Teas Ceylon (Pvt) Ltd', 'Sponsor': 'N/A', 'Location': 'Z3-C47 ', 'Pavilion': 'N/A', 'Hall Number': "Za'abeel Hall 3", 'Country': 'Sri Lanka', 'Company Type': 'Distributors/Reseller'},
    {'Name': 'Virto Group', 'Sponsor': 'N/A', 'Location': '606 ', 'Pavilion': '15', 'Hall Number': 'Hall 6', 'Country': 'Spain', 'Company Type': 'Manufacturer'},
    {'Name': 'Vishaka Raisins', 'Sponsor': 'N/A', 'Location': 'Z5-G15 ', 'Pavilion': '5', 'Hall Number': "Za'abeel Hall 5", 'Country': 'India', 'Company Type': 'Manufacturer'},
    {'Name': 'VISIMEX CORPORATION', 'Sponsor': 'N/A', 'Location': 'M-G48 ', 'Pavilion': '3', 'Hall Number': 'Shk Maktoum Hall', 'Country': 'Vietnam', 'Company Type': 'Manufacturer'},
    {'Name': 'Visnukumar Traders Pvt. Ltd.', 'Sponsor': 'N/A', 'Location': 'S-A15 ', 'Pavilion': '5', 'Hall Number': 'Trade Centre Arena', 'Country': 'India', 'Company Type': 'Manufacturer'},
    {'Name': 'Vitafood SH.P.K', 'Sponsor': 'N/A', 'Location': 'MP-K18 ', 'Pavilion': 'N/A', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'Kosovo', 'Company Type': 'N/A'},
    {'Name': 'Vitakai', 'Sponsor': 'N/A', 'Location': 'S-K24 ', 'Pavilion': '5', 'Hall Number': 'Trade Centre Arena', 'Country': 'Chile', 'Company Type': 'Manufacturer'},
    {'Name': 'VITAL FOODS FACTORY LLC', 'Sponsor': 'N/A', 'Location': 'CC1-23 ', 'Pavilion': '20', 'Hall Number': 'Concourse 1', 'Country': 'United Arab Emirates', 'Company Type': 'Manufacturer'},
    {'Name': 'Vitalus Nutrition Inc.', 'Sponsor': 'N/A', 'Location': 'G2-22 ', 'Pavilion': '10', 'Hall Number': 'Hall 2', 'Country': 'Canada', 'Company Type': 'Manufacturer'},
    {'Name': 'Vitamizu', 'Sponsor': 'N/A', 'Location': 'Z2-A43 ', 'Pavilion': 'N/A', 'Hall Number': "Za'abeel Hall 2", 'Country': 'Poland', 'Company Type': 'Manufacturer'},
    {'Name': 'Vitaz Food & Beverages Pvt. Ltd', 'Sponsor': 'N/A', 'Location': 'S-A10 ', 'Pavilion': '5', 'Hall Number': 'Trade Centre Arena', 'Country': 'India', 'Company Type': 'Manufacturer'},
    {'Name': 'Vitecer', 'Sponsor': 'N/A', 'Location': 'S1-G55 ', 'Pavilion': '5', 'Hall Number': 'Shk Saeed Hall 1', 'Country': 'Hungary', 'Company Type': 'Manufacturer'},
    {'Name': 'Vitelco B.V.', 'Sponsor': 'N/A', 'Location': 'D3-20 ', 'Pavilion': '15', 'Hall Number': 'Hall 3', 'Country': 'Netherlands', 'Company Type': 'Manufacturer'},
    {'Name': 'Viterra', 'Sponsor': 'N/A', 'Location': 'Z4-G22 ', 'Pavilion': 'N/A', 'Hall Number': "Za'abeel Hall 4", 'Country': 'Canada', 'Company Type': 'Importer/ Trader/ Wholesaler'},
    {'Name': 'VITO AG', 'Sponsor': 'N/A', 'Location': 'S3-B3 ', 'Pavilion': '10', 'Hall Number': 'Shk Saeed Hall 3', 'Country': 'United Arab Emirates', 'Company Type': 'Distributors/Reseller'},
    {'Name': 'VIT TRADE LLC', 'Sponsor': 'N/A', 'Location': 'Z5-B14 ', 'Pavilion': '3', 'Hall Number': "Za'abeel Hall 5", 'Country': 'Russian Federation', 'Company Type': 'Importer/ Trader/ Wholesaler'},
    {'Name': 'VIVAKS', 'Sponsor': 'N/A', 'Location': 'ZL-20 ', 'Pavilion': '20', 'Hall Number': "Za'abeel Hall 3", 'Country': 'North Macedonia', 'Company Type': 'Manufacturer'},
    {'Name': 'VLAM vzw', 'Sponsor': 'N/A', 'Location': 'E1-2 ', 'Pavilion': '25', 'Hall Number': 'Hall 1', 'Country': 'Belgium', 'Company Type': 'Trade Promotion Organization'},
    {'Name': 'VNP FOOD', 'Sponsor': 'N/A', 'Location': 'MP-J8 ', 'Pavilion': '10', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'Thailand', 'Company Type': 'Manufacturer'},
    {'Name': 'Volcke Aerosol Italy S.r.l.', 'Sponsor': 'N/A', 'Location': 'S1-C14 ', 'Pavilion': '5', 'Hall Number': 'Shk Saeed Hall 1', 'Country': 'Italy', 'Company Type': 'Manufacturer'},
    {'Name': 'Volkovysk OJSC Bellakt', 'Sponsor': 'N/A', 'Location': 'D1-2 ', 'Pavilion': '5', 'Hall Number': 'Hall 1', 'Country': 'Belarus', 'Company Type': 'Caterer'},
    {'Name': 'Vologodskoe Morozhenoe LLC (Iceberry Group)', 'Sponsor': 'N/A', 'Location': 'S-D48 ', 'Pavilion': 'N/A', 'Hall Number': 'Trade Centre Arena', 'Country': 'Russian Federation', 'Company Type': 'Manufacturer'},
    {'Name': 'Voloshkove Pole LLC', 'Sponsor': 'N/A', 'Location': 'S2-D66 ', 'Pavilion': '5', 'Hall Number': 'Shk Saeed Hall 2', 'Country': 'Ukraine', 'Company Type': 'Manufacturer'},
    {'Name': 'Volys Star', 'Sponsor': 'N/A', 'Location': 'S2-D49 ', 'Pavilion': '5', 'Hall Number': 'Shk Saeed Hall 2', 'Country': 'Belgium', 'Company Type': 'Manufacturer'},
    {'Name': 'Vonk Culinary Cheese', 'Sponsor': 'N/A', 'Location': 'F1-3 ', 'Pavilion': '5', 'Hall Number': 'Hall 1', 'Country': 'Belgium', 'Company Type': 'Manufacturer'},
    {'Name': 'Vossko do Brasil Alimentos Congelados Ltd.', 'Sponsor': 'N/A', 'Location': 'E3-37 ', 'Pavilion': '5', 'Hall Number': 'Hall 3', 'Country': 'Brazil', 'Company Type': 'Food Service'},
    {'Name': 'VRB Consumer Products Pvt. Ltd.', 'Sponsor': 'N/A', 'Location': 'S-A45 ', 'Pavilion': '15', 'Hall Number': 'Trade Centre Arena', 'Country': 'India', 'Company Type': 'Manufacturer'},
    {'Name': 'Vreugdenhil Dairy Foods', 'Sponsor': 'N/A', 'Location': 'E1-34 ', 'Pavilion': '20', 'Hall Number': 'Hall 1', 'Country': 'Netherlands', 'Company Type': 'Manufacturer'},
    {'Name': 'VRS Foods Ltd.', 'Sponsor': 'N/A', 'Location': 'G2-33 ', 'Pavilion': '15', 'Hall Number': 'Hall 2', 'Country': 'India', 'Company Type': 'Manufacturer'},
    {'Name': 'VTC TRADE GIDA', 'Sponsor': 'N/A', 'Location': 'S2-E53 ', 'Pavilion': '5', 'Hall Number': 'Shk Saeed Hall 2', 'Country': 'Ukraine', 'Company Type': 'Importer/ Trader/ Wholesaler'},
    {'Name': 'V&V Walsh', 'Sponsor': 'N/A', 'Location': 'B4-49 ', 'Pavilion': 'N/A', 'Hall Number': 'Hall 4', 'Country': 'Australia', 'Company Type': 'Importer/ Trader/ Wholesaler'},
    {'Name': 'Wafrah for Industry and Development', 'Sponsor': 'N/A', 'Location': 'R-C33 ', 'Pavilion': '5', 'Hall Number': 'Shk Rashid Hall', 'Country': 'Saudi Arabia', 'Company Type': 'Manufacturer'},
    {'Name': 'Wagyu Biltong Co.', 'Sponsor': 'N/A', 'Location': 'S-370 ', 'Pavilion': '5', 'Hall Number': 'Trade Centre Arena', 'Country': 'Australia', 'Company Type': 'Manufacturer'},
    {'Name': 'Wais Sodais Ltd', 'Sponsor': 'N/A', 'Location': 'MP-E14 ', 'Pavilion': '3', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'Afghanistan', 'Company Type': 'Importer/ Trader/ Wholesaler'},
    {'Name': 'WAKALEX FOR INDUSTRY AND TRADE CO', 'Sponsor': 'N/A', 'Location': 'Z4-F9 ', 'Pavilion': '5', 'Hall Number': "Za'abeel Hall 4", 'Country': 'Egypt', 'Company Type': 'Importer/ Trader/ Wholesaler'},
    {'Name': 'waleed sabbahi establishment', 'Sponsor': 'N/A', 'Location': 'MP-G10 ', 'Pavilion': '10', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'United Arab Emirates', 'Company Type': 'Importer/ Trader/ Wholesaler'},
    {'Name': 'Walnuts ge Ltd', 'Sponsor': 'N/A', 'Location': 'S-M44 ', 'Pavilion': '5', 'Hall Number': 'Trade Centre Arena', 'Country': 'Georgia', 'Company Type': 'Manufacturer'},
    {'Name': 'WAMMCO International Pty Ltd', 'Sponsor': 'N/A', 'Location': 'H3-33 ', 'Pavilion': '5', 'Hall Number': 'Hall 3', 'Country': 'Australia', 'Company Type': 'Manufacturer'},
    {'Name': 'Wana Beverage JSC', 'Sponsor': 'N/A', 'Location': 'MP-L20 ', 'Pavilion': '5', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'Vietnam', 'Company Type': 'Manufacturer'},
    {'Name': 'Waqar Rice Mills', 'Sponsor': 'N/A', 'Location': 'Z6-F16 ', 'Pavilion': '25', 'Hall Number': "Za'abeel Hall 6", 'Country': 'Pakistan', 'Company Type': 'Manufacturer'},
    {'Name': 'Wardat Al Mashreq Food Co.', 'Sponsor': 'N/A', 'Location': '137 ', 'Pavilion': '15', 'Hall Number': 'Hall 1', 'Country': 'Saudi Arabia', 'Company Type': 'Manufacturer'},
    {'Name': 'Ward McKenzie', 'Sponsor': 'N/A', 'Location': 'S-K65 ', 'Pavilion': 'N/A', 'Hall Number': 'Trade Centre Arena', 'Country': 'Australia', 'Company Type': 'Manufacturer'},
    {'Name': 'Warnez patatoes', 'Sponsor': 'N/A', 'Location': 'S2-C58 ', 'Pavilion': '3', 'Hall Number': 'Shk Saeed Hall 2', 'Country': 'Belgium', 'Company Type': 'Importer/ Trader/ Wholesaler'},
    {'Name': 'Wasela LTD', 'Sponsor': 'N/A', 'Location': 'MP-F111 ', 'Pavilion': '3', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'Afghanistan', 'Company Type': 'Importer/ Trader/ Wholesaler'},
    {'Name': 'WATAP (THAILAND) CO., LTD.', 'Sponsor': 'N/A', 'Location': 'R-M38 ', 'Pavilion': '3', 'Hall Number': 'Shk Rashid Hall', 'Country': 'Thailand', 'Company Type': 'Importer/ Trader/ Wholesaler'},
    {'Name': 'Wayamba DC & Oil Mills (Pvt) Ltd', 'Sponsor': 'N/A', 'Location': 'R-F4 ', 'Pavilion': '3', 'Hall Number': 'Shk Rashid Hall', 'Country': 'Sri Lanka', 'Company Type': 'Manufacturer'},
    {'Name': 'Weaver Popcorn Bulk, LLC', 'Sponsor': 'N/A', 'Location': 'S3-C56 ', 'Pavilion': 'N/A', 'Hall Number': 'Shk Saeed Hall 3', 'Country': 'United States of America', 'Company Type': 'Manufacturer'},
    {'Name': 'Wegdam Food Link B.V.', 'Sponsor': 'N/A', 'Location': 'D3-28 ', 'Pavilion': '15', 'Hall Number': 'Hall 3', 'Country': 'Netherlands', 'Company Type': 'Importer/ Trader/ Wholesaler'},
    {'Name': 'We Get Any Stock', 'Sponsor': 'N/A', 'Location': 'S1-B64 ', 'Pavilion': 'N/A', 'Hall Number': 'Shk Saeed Hall 1', 'Country': 'United Kingdom', 'Company Type': 'Importer/ Trader/ Wholesaler'},
    {'Name': 'Welsh Government', 'Sponsor': 'N/A', 'Location': 'S1-B10 ', 'Pavilion': 'N/A', 'Hall Number': 'Shk Saeed Hall 1', 'Country': 'United Kingdom', 'Company Type': 'Government/Government Agency'},
    {'Name': 'WEST EUNOMIA GROUP LLC', 'Sponsor': 'N/A', 'Location': 'ZP-C7 ', 'Pavilion': '3', 'Hall Number': "Za'abeel Plaza", 'Country': 'Ukraine', 'Company Type': 'Manufacturer'},
    {'Name': 'WF Distribution', 'Sponsor': 'N/A', 'Location': 'G3-26 ', 'Pavilion': '3', 'Hall Number': 'Hall 3', 'Country': 'France', 'Company Type': 'N/A'},
    {'Name': "What's Cooking", 'Sponsor': 'N/A', 'Location': 'S1-B10 ', 'Pavilion': '10', 'Hall Number': 'Shk Saeed Hall 1', 'Country': 'United Kingdom', 'Company Type': 'Manufacturer'},
    {'Name': 'Whip-it!', 'Sponsor': 'N/A', 'Location': 'MP-L15 ', 'Pavilion': '5', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'United States of America', 'Company Type': 'Food Service'},
    {'Name': 'White Lion Nuts S.A.C.', 'Sponsor': 'N/A', 'Location': 'S-K29 ', 'Pavilion': 'N/A', 'Hall Number': 'Trade Centre Arena', 'Country': 'Peru', 'Company Type': 'N/A'},
    {'Name': 'White Pearl Group', 'Sponsor': 'N/A', 'Location': 'Z6-170 ', 'Pavilion': '15', 'Hall Number': "Za'abeel Hall 6", 'Country': 'Pakistan', 'Company Type': 'Manufacturer'},
    {'Name': "White's Oats", 'Sponsor': 'N/A', 'Location': 'S1-A44 ', 'Pavilion': '5', 'Hall Number': 'Shk Saeed Hall 1', 'Country': 'United Kingdom', 'Company Type': 'Manufacturer'},
    {'Name': 'Whole Grain (Dalian) Foods Technology Co.,Ltd', 'Sponsor': 'N/A', 'Location': 'MP2-E22 ', 'Pavilion': '3', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'China', 'Company Type': 'Manufacturer'},
    {'Name': 'Wichy Plantation (Pvt) Ltd', 'Sponsor': 'N/A', 'Location': 'MP2-L25 ', 'Pavilion': '3', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'Sri Lanka', 'Company Type': 'Food Service'},
    {'Name': 'WIDE TROPISM TRADING SDN BHD', 'Sponsor': 'N/A', 'Location': 'MP2-B3 ', 'Pavilion': '3', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'Malaysia', 'Company Type': 'Manufacturer'},
    {'Name': 'Widriss S.A.L', 'Sponsor': 'N/A', 'Location': '332 ', 'Pavilion': '15', 'Hall Number': 'Hall 3', 'Country': 'Lebanon', 'Company Type': 'Distributors/Reseller'},
    {'Name': 'Wijaya products Pvt Ltd.', 'Sponsor': 'N/A', 'Location': 'R-G9 ', 'Pavilion': 'N/A', 'Hall Number': 'Shk Rashid Hall', 'Country': 'Sri Lanka', 'Company Type': 'Manufacturer'},
    {'Name': 'Wilbur Packing Company', 'Sponsor': 'N/A', 'Location': 'S3-E28 ', 'Pavilion': '3', 'Hall Number': 'Shk Saeed Hall 3', 'Country': 'United States of America', 'Company Type': 'Manufacturer'},
    {'Name': 'WILCOM TRADING PLC', 'Sponsor': 'N/A', 'Location': 'Z4-A40 ', 'Pavilion': '15', 'Hall Number': "Za'abeel Hall 4", 'Country': 'Ethiopia', 'Company Type': 'Importer/ Trader/ Wholesaler'},
    {'Name': 'Wilhelm Reuss GmbH & Co. KG', 'Sponsor': 'N/A', 'Location': 'S3-A66 ', 'Pavilion': '5', 'Hall Number': 'Shk Saeed Hall 2', 'Country': 'Germany', 'Company Type': 'Manufacturer'},
    {'Name': 'Willys ACV', 'Sponsor': 'N/A', 'Location': 'S1-B44 ', 'Pavilion': 'N/A', 'Hall Number': 'Shk Saeed Hall 1', 'Country': 'United Kingdom', 'Company Type': 'N/A'},
    {'Name': 'Winland Foods, Inc', 'Sponsor': 'N/A', 'Location': 'S3-D67 ', 'Pavilion': 'N/A', 'Hall Number': 'Shk Saeed Hall 3', 'Country': 'United States of America', 'Company Type': 'Manufacturer'},
    {'Name': 'Wisconsin Department of Agriculture, Trade and Consumer Protection', 'Sponsor': 'N/A', 'Location': 'S3-C68 ', 'Pavilion': '3', 'Hall Number': 'Shk Saeed Hall 3', 'Country': 'United States of America', 'Company Type': 'Agency'},
    {'Name': 'Wismettac Foods, Inc.', 'Sponsor': 'N/A', 'Location': 'S-153 ', 'Pavilion': '5', 'Hall Number': 'Trade Centre Arena', 'Country': 'Japan', 'Company Type': 'Importer/ Trader/ Wholesaler'},
    {'Name': 'Wofco', 'Sponsor': 'N/A', 'Location': 'S2-L17 ', 'Pavilion': '5', 'Hall Number': 'Shk Saeed Hall 2', 'Country': 'Spain', 'Company Type': 'Importer/ Trader/ Wholesaler'},
    {'Name': 'Wonder Bakery LLC', 'Sponsor': 'N/A', 'Location': 'A5-35 ', 'Pavilion': '20', 'Hall Number': 'Hall 5', 'Country': 'United Arab Emirates', 'Company Type': 'N/A'},
    {'Name': 'Wonderful Pistachios & Almonds', 'Sponsor': 'N/A', 'Location': 'S3-F26 ', 'Pavilion': '20', 'Hall Number': 'Shk Saeed Hall 3', 'Country': 'Belgium', 'Company Type': 'Manufacturer'},
    {'Name': 'Wonnapob Co., Ltd.', 'Sponsor': 'N/A', 'Location': 'Z4-D55 ', 'Pavilion': '3', 'Hall Number': "Za'abeel Hall 4", 'Country': 'Thailand', 'Company Type': 'Manufacturer'},
    {'Name': 'Woodward Foods Australia', 'Sponsor': 'N/A', 'Location': 'A4-50 ', 'Pavilion': '5', 'Hall Number': 'Hall 4', 'Country': 'Australia', 'Company Type': 'Manufacturer'},
    {'Name': 'WorkSmart for Events Management W.L.L.', 'Sponsor': 'N/A', 'Location': 'R-H4 ', 'Pavilion': 'N/A', 'Hall Number': 'Shk Rashid Hall', 'Country': 'Bahrain', 'Company Type': 'N/A'},
    {'Name': 'World Deal Traders', 'Sponsor': 'N/A', 'Location': 'S3-E35 ', 'Pavilion': '5', 'Hall Number': 'Shk Saeed Hall 3', 'Country': 'United States of America', 'Company Type': 'Distributors/Reseller'},
    {'Name': 'W.S. Karoulias Single Member S.A', 'Sponsor': 'N/A', 'Location': 'S1-G60 ', 'Pavilion': 'N/A', 'Hall Number': 'Shk Saeed Hall 1', 'Country': 'Greece', 'Company Type': 'Distributors/Reseller'},
    {'Name': 'WUSATA', 'Sponsor': 'N/A', 'Location': 'S3-E4 ', 'Pavilion': '0', 'Hall Number': 'Shk Saeed Hall 3', 'Country': 'United States of America', 'Company Type': 'Trade Promotion Organization'},
    {'Name': 'WUYUAN COUNTY DAFENG OIL FOOD CO.,LTD', 'Sponsor': 'N/A', 'Location': 'MP2-F32 ', 'Pavilion': '3', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'China', 'Company Type': 'Manufacturer'},
    {'Name': 'Wuyuan County Fucaisheng Commercial Co.,Ltd', 'Sponsor': 'N/A', 'Location': 'MP2-F28 ', 'Pavilion': '3', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'China', 'Company Type': 'Manufacturer'},
    {'Name': 'Wuyuan County Qianhongtai Commercial Co.,Ltd', 'Sponsor': 'N/A', 'Location': 'MP2-F22 ', 'Pavilion': '3', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'China', 'Company Type': 'Manufacturer'},
    {'Name': 'Wuyuan County Sanrong Trading Co.,Ltd', 'Sponsor': 'N/A', 'Location': 'MP2-H25 ', 'Pavilion': '3', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'China', 'Company Type': 'Manufacturer'},
    {'Name': 'WUZHOU HONGJING TRADING CO.,LTD', 'Sponsor': 'N/A', 'Location': 'MP2-G21 ', 'Pavilion': '3', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'China', 'Company Type': 'Manufacturer'},
    {'Name': 'Wyke Farms', 'Sponsor': 'N/A', 'Location': 'B2-21 ', 'Pavilion': 'N/A', 'Hall Number': 'Hall 2', 'Country': 'United Kingdom', 'Company Type': 'N/A'},
    {'Name': 'Xiamen Pak Shing Imp & Exp Co.,Ltd.', 'Sponsor': 'N/A', 'Location': 'MP2-H29 ', 'Pavilion': '3', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'China', 'Company Type': 'Manufacturer'},
    {'Name': 'Xinjiang Guannong Tomato Products Co., LTD', 'Sponsor': 'N/A', 'Location': 'MP2-C32 ', 'Pavilion': '3', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'China', 'Company Type': 'Manufacturer'},
    {'Name': 'Xinjiang Pollo Food Co.,Ltd.', 'Sponsor': 'N/A', 'Location': 'MP2-C18 ', 'Pavilion': '3', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'China', 'Company Type': 'Manufacturer'},
    {'Name': 'XL Energy Marketing Sp. z o. o.', 'Sponsor': 'N/A', 'Location': 'Z3-A53 ', 'Pavilion': '10', 'Hall Number': "Za'abeel Hall 3", 'Country': 'Poland', 'Company Type': 'Manufacturer'},
    {'Name': 'Xuzhou Holdwater Food Co.Ltd.', 'Sponsor': 'N/A', 'Location': 'MP2-F30 ', 'Pavilion': '3', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'China', 'Company Type': 'Manufacturer'},
    {'Name': 'YAAQOUB HAMDAN FOODSTUFF TRADING CO LLC', 'Sponsor': 'N/A', 'Location': 'Z6-140 ', 'Pavilion': '10', 'Hall Number': "Za'abeel Hall 6", 'Country': 'United Arab Emirates', 'Company Type': 'N/A'},
    {'Name': 'YA HALA FOR MANUFACTURE OF ARABIC SWEETS L.L.C', 'Sponsor': 'N/A', 'Location': 'T-G10 ', 'Pavilion': 'N/A', 'Hall Number': 'The Pavilion', 'Country': 'United Arab Emirates', 'Company Type': 'N/A'},
    {'Name': 'Yamaishi Co., Ltd.', 'Sponsor': 'N/A', 'Location': 'MP2-B28 ', 'Pavilion': '5', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'Japan', 'Company Type': 'Manufacturer'},
    {'Name': 'Yantai Eversun Food Co.,Ltd', 'Sponsor': 'N/A', 'Location': 'MP2-G27 ', 'Pavilion': '3', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'China', 'Company Type': 'Manufacturer'},
    {'Name': 'Yan Wal Yun Corporation Group Co., Ltd.', 'Sponsor': 'N/A', 'Location': 'R-N15 ', 'Pavilion': '3', 'Hall Number': 'Shk Rashid Hall', 'Country': 'Thailand', 'Company Type': 'Manufacturer'},
    {'Name': 'Yan Yan International Philippines, Inc.', 'Sponsor': 'N/A', 'Location': 'R-164 ', 'Pavilion': '3', 'Hall Number': 'Shk Rashid Hall', 'Country': 'Philippines', 'Company Type': 'Manufacturer'},
    {'Name': 'Yarra Valley Dairy', 'Sponsor': 'N/A', 'Location': 'S-K65 ', 'Pavilion': '3', 'Hall Number': 'Trade Centre Arena', 'Country': 'Australia', 'Company Type': 'Manufacturer'},
    {'Name': 'Yasmina Company LLC', 'Sponsor': 'N/A', 'Location': 'S-151C ', 'Pavilion': '3', 'Hall Number': 'Trade Centre Arena', 'Country': 'Ukraine', 'Company Type': 'Manufacturer'},
    {'Name': 'Yatha Trading JLT', 'Sponsor': 'N/A', 'Location': 'C8-20 ', 'Pavilion': '35', 'Hall Number': 'Hall 8', 'Country': 'Yemen', 'Company Type': 'Manufacturer'},
    {'Name': 'YAW! SAPICO', 'Sponsor': 'N/A', 'Location': 'MP2-250 ', 'Pavilion': 'N/A', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'Moldova', 'Company Type': 'N/A'},
    {'Name': 'Yayla Agro Gida San Ve Tic AS', 'Sponsor': 'N/A', 'Location': 'Z5-B39 ', 'Pavilion': '20', 'Hall Number': "Za'abeel Hall 5", 'Country': 'Türkiye', 'Company Type': 'Manufacturer'},
    {'Name': 'Yayla Pan', 'Sponsor': 'N/A', 'Location': 'S-D23 ', 'Pavilion': '5', 'Hall Number': 'Trade Centre Arena', 'Country': 'Serbia', 'Company Type': 'Manufacturer'},
    {'Name': 'Yayla-Tuerk Lebensmittelvertrieb GmbH', 'Sponsor': 'N/A', 'Location': 'S3-B47 ', 'Pavilion': 'N/A', 'Hall Number': 'Shk Saeed Hall 3', 'Country': 'Germany', 'Company Type': 'Importer/ Trader/ Wholesaler'},
    {'Name': 'YEDNIST GROUP', 'Sponsor': 'N/A', 'Location': 'ZP-C5 ', 'Pavilion': '3', 'Hall Number': "Za'abeel Plaza", 'Country': 'Ukraine', 'Company Type': 'Manufacturer'},
    {'Name': 'Yeni Tekozel Markalı Urunler Dagitim Hizmetleri A.S', 'Sponsor': 'N/A', 'Location': 'MP-H26 ', 'Pavilion': '25', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'Türkiye', 'Company Type': 'Manufacturer'},
    {'Name': 'Yerba Mate Pipore', 'Sponsor': 'N/A', 'Location': 'Z2-B77 ', 'Pavilion': '3', 'Hall Number': "Za'abeel Hall 2", 'Country': 'Argentina', 'Company Type': 'Manufacturer'},
    {'Name': 'Yerbatera Hoja Verde S.R.L.', 'Sponsor': 'N/A', 'Location': 'Z2-B79 ', 'Pavilion': '3', 'Hall Number': "Za'abeel Hall 2", 'Country': 'Argentina', 'Company Type': 'Manufacturer'},
    {'Name': 'Yokai Sales & Marketing GmbH', 'Sponsor': 'N/A', 'Location': 'Z3-F19 ', 'Pavilion': 'N/A', 'Hall Number': "Za'abeel Hall 3", 'Country': 'Germany', 'Company Type': 'Start-Up'},
    {'Name': 'Yonca Gida Sanayi Isletmeleri Ic Ve Dis Ticaret A.S.', 'Sponsor': 'N/A', 'Location': 'M-C13 ', 'Pavilion': '10', 'Hall Number': 'Shk Maktoum Hall', 'Country': 'Türkiye', 'Company Type': 'Manufacturer'},
    {'Name': 'YOOK Production AS', 'Sponsor': 'N/A', 'Location': 'S-I61 ', 'Pavilion': 'N/A', 'Hall Number': 'Trade Centre Arena', 'Country': 'Estonia', 'Company Type': 'Manufacturer'},
    {'Name': 'Yorkvale Trading', 'Sponsor': 'N/A', 'Location': 'H2-19 ', 'Pavilion': '10', 'Hall Number': 'Hall 2', 'Country': 'Canada', 'Company Type': 'Importer/ Trader/ Wholesaler'},
    {'Name': 'Yorsan Sut Ve Sut Urunleri San Ve Tic A.S', 'Sponsor': 'N/A', 'Location': 'C3-11 ', 'Pavilion': 'N/A', 'Hall Number': 'Hall 3', 'Country': 'Türkiye', 'Company Type': 'Manufacturer'},
    {'Name': 'Yorukoglu Sut Ve Urunleri San. Tic. A.S', 'Sponsor': 'N/A', 'Location': 'E2-44 ', 'Pavilion': '15', 'Hall Number': 'Hall 2', 'Country': 'Türkiye', 'Company Type': 'Manufacturer'},
    {'Name': 'Yorukogullari Gida San. Ve Tic. A.S.', 'Sponsor': 'N/A', 'Location': 'Z5-A4 ', 'Pavilion': '15', 'Hall Number': "Za'abeel Hall 5", 'Country': 'Türkiye', 'Company Type': 'Manufacturer'},
    {'Name': 'Young Poong Co. Ltd.', 'Sponsor': 'N/A', 'Location': 'MP-D2 ', 'Pavilion': '15', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'Republic Of Korea', 'Company Type': 'Manufacturer'},
    {'Name': "YOUNG'S PRIVATE LIMITED", 'Sponsor': 'N/A', 'Location': 'Z6-A14 ', 'Pavilion': '15', 'Hall Number': "Za'abeel Hall 6", 'Country': 'Pakistan', 'Company Type': 'Manufacturer'},
    {'Name': 'yourharvest AG', 'Sponsor': 'N/A', 'Location': 'S2-E3 ', 'Pavilion': '10', 'Hall Number': 'Shk Saeed Hall 2', 'Country': 'Switzerland', 'Company Type': 'Distributors/Reseller'},
    {'Name': 'Yousify General Trading Co.', 'Sponsor': 'N/A', 'Location': 'R-Q33 ', 'Pavilion': '15', 'Hall Number': 'Shk Rashid Hall', 'Country': 'United Arab Emirates', 'Company Type': 'Importer/ Trader/ Wholesaler'},
    {'Name': 'YUMIS', 'Sponsor': 'N/A', 'Location': 'S-C22 ', 'Pavilion': '5', 'Hall Number': 'Trade Centre Arena', 'Country': 'Serbia', 'Company Type': 'N/A'},
    {'Name': 'Yummy Bites - PT Leon Boga Sentosa', 'Sponsor': 'N/A', 'Location': 'M-H50 ', 'Pavilion': '3', 'Hall Number': 'Shk Maktoum Hall', 'Country': 'Indonesia', 'Company Type': 'Importer/ Trader/ Wholesaler'},
    {'Name': 'Yupekchi Economic Society', 'Sponsor': 'N/A', 'Location': 'MP-246 ', 'Pavilion': 'N/A', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'Turkmenistan', 'Company Type': 'N/A'},
    {'Name': 'YUYAO YIJIA FOOD TECHNOLOGY CO.,LTD', 'Sponsor': 'N/A', 'Location': 'MP2-E26 ', 'Pavilion': '3', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'China', 'Company Type': 'Manufacturer'},
    {'Name': 'Zadna Dates Trading', 'Sponsor': 'N/A', 'Location': 'MP-A29 ', 'Pavilion': 'N/A', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'Saudi Arabia', 'Company Type': 'N/A'},
    {'Name': 'Zadona Agri Industrial Co', 'Sponsor': 'N/A', 'Location': 'R-M7 ', 'Pavilion': 'N/A', 'Hall Number': 'Shk Rashid Hall', 'Country': 'Palestine', 'Company Type': 'Manufacturer'},
    {'Name': 'Zahr Al Bustan', 'Sponsor': 'N/A', 'Location': 'TP-150 ', 'Pavilion': 'N/A', 'Hall Number': 'The Pavilion', 'Country': 'France', 'Company Type': 'Manufacturer'},
    {'Name': 'Zain Group', 'Sponsor': 'N/A', 'Location': 'MP-H13 ', 'Pavilion': '10', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'Türkiye', 'Company Type': 'Manufacturer'},
    {'Name': 'Zaiqa Food Industries', 'Sponsor': 'N/A', 'Location': 'Z6-C50 ', 'Pavilion': 'N/A', 'Hall Number': "Za'abeel Hall 6", 'Country': 'Pakistan', 'Company Type': 'N/A'},
    {'Name': 'Zakir Sha Exports', 'Sponsor': 'N/A', 'Location': 'Z2-F30 ', 'Pavilion': '3', 'Hall Number': "Za'abeel Hall 2", 'Country': 'Sri Lanka', 'Company Type': 'Manufacturer'},
    {'Name': 'Zaki Tejarat Espadana Food Ind', 'Sponsor': 'N/A', 'Location': 'R-N48 ', 'Pavilion': '10', 'Hall Number': 'Shk Rashid Hall', 'Country': 'Iran', 'Company Type': 'N/A'},
    {'Name': 'Zalmhuys Group', 'Sponsor': 'N/A', 'Location': 'S2-F14 ', 'Pavilion': '10', 'Hall Number': 'Shk Saeed Hall 2', 'Country': 'Netherlands', 'Company Type': 'Manufacturer'},
    {'Name': 'Zamil Food Industries Co. Ltd.', 'Sponsor': 'N/A', 'Location': 'G2-2 ', 'Pavilion': '20', 'Hall Number': 'Hall 2', 'Country': 'Saudi Arabia', 'Company Type': 'Food Service'},
    {'Name': 'Zamzam Bros Co.', 'Sponsor': 'N/A', 'Location': 'R-E39 ', 'Pavilion': '15', 'Hall Number': 'Shk Rashid Hall', 'Country': 'Jordan', 'Company Type': 'Manufacturer'},
    {'Name': 'Zanae S.A.', 'Sponsor': 'N/A', 'Location': 'S1-120 ', 'Pavilion': '10', 'Hall Number': 'Shk Saeed Hall 1', 'Country': 'Greece', 'Company Type': 'Manufacturer'},
    {'Name': 'Zanchetta Alimentos Ltda', 'Sponsor': 'N/A', 'Location': 'C3-33 ', 'Pavilion': '5', 'Hall Number': 'Hall 3', 'Country': 'Brazil', 'Company Type': 'Retailer'},
    {'Name': 'Zanchetta Alimentos Ltda', 'Sponsor': 'N/A', 'Location': 'D3-42 ', 'Pavilion': '5', 'Hall Number': 'Hall 3', 'Country': 'Brazil', 'Company Type': 'Manufacturer'},
    {'Name': 'Zanetti S.P.A.', 'Sponsor': 'N/A', 'Location': 'B1-28 ', 'Pavilion': 'N/A', 'Hall Number': 'Hall 1', 'Country': 'Italy', 'Company Type': 'Distributors/Reseller'},
    {'Name': 'Zardolui Isfara, LLC', 'Sponsor': 'N/A', 'Location': 'MP-L2 ', 'Pavilion': '3', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'Tajikistan', 'Company Type': 'Manufacturer'},
    {'Name': 'Zargarzadeh Commercial Co.', 'Sponsor': 'N/A', 'Location': 'R-Q34 ', 'Pavilion': '15', 'Hall Number': 'Shk Rashid Hall', 'Country': 'Iran', 'Company Type': 'N/A'},
    {'Name': 'Zarin Sannat Sarv', 'Sponsor': 'N/A', 'Location': 'T-D14 ', 'Pavilion': '20', 'Hall Number': 'The Pavilion', 'Country': 'Iran', 'Company Type': 'Manufacturer'},
    {'Name': 'Zenith Drinks Private Limited', 'Sponsor': 'N/A', 'Location': 'S-B63 ', 'Pavilion': '5', 'Hall Number': 'Trade Centre Arena', 'Country': 'India', 'Company Type': 'Distributors/Reseller'},
    {'Name': 'ZENKO Superfoods Pte Ltd', 'Sponsor': 'N/A', 'Location': 'MP2-258 ', 'Pavilion': '10', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'Singapore', 'Company Type': 'N/A'},
    {'Name': 'Zer Yag Sanayi Ve Ticaret A.S.', 'Sponsor': 'N/A', 'Location': 'Z1-C39 ', 'Pavilion': '20', 'Hall Number': "Za'abeel Hall 1", 'Country': 'Türkiye', 'Company Type': 'Manufacturer'},
    {'Name': 'Zeyaratjah Ltd', 'Sponsor': 'N/A', 'Location': 'MP-F15 ', 'Pavilion': '3', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'Afghanistan', 'Company Type': 'Food Service'},
    {'Name': 'ZHANGZHOU FWUYIH FOODS CO., LTD.', 'Sponsor': 'N/A', 'Location': 'MP2-E31 ', 'Pavilion': '3', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'China', 'Company Type': 'Manufacturer'},
    {'Name': 'Zhaoqing DY Trading Co., LTD.', 'Sponsor': 'N/A', 'Location': 'MP2-G29 ', 'Pavilion': '3', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'China', 'Company Type': 'Importer/ Trader/ Wholesaler'},
    {'Name': 'Zhenjiang Heng Goodwill Food Co.,Ltd', 'Sponsor': 'N/A', 'Location': 'MP2-D29 ', 'Pavilion': '3', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'China', 'Company Type': 'Manufacturer'},
    {'Name': 'Zigui County Qugu Food Co., Ltd', 'Sponsor': 'N/A', 'Location': 'MP2-E18 ', 'Pavilion': '3', 'Hall Number': 'Al Mustaqbal Plaza', 'Country': 'China', 'Company Type': 'Manufacturer'},
    {'Name': 'Zini Prodotti Alimentari S.P.A.', 'Sponsor': 'N/A', 'Location': 'B1-27 ', 'Pavilion': '0', 'Hall Number': 'Hall 1', 'Country': 'Italy', 'Company Type': 'N/A'},
    {'Name': 'Zirve Drinks', 'Sponsor': 'N/A', 'Location': 'Z1-B36 ', 'Pavilion': '15', 'Hall Number': "Za'abeel Hall 1", 'Country': 'Türkiye', 'Company Type': 'Manufacturer'},
    {'Name': 'ZIV LTD.', 'Sponsor': 'N/A', 'Location': 'S1-170 ', 'Pavilion': '15', 'Hall Number': 'Shk Saeed Hall 1', 'Country': 'Bulgaria', 'Company Type': 'Manufacturer'},
    {'Name': 'ZM FOOD, JSC', 'Sponsor': 'N/A', 'Location': 'S-L64 ', 'Pavilion': '5', 'Hall Number': 'Trade Centre Arena', 'Country': 'Lithuania', 'Company Type': 'Manufacturer'},
    {'Name': 'Zott SE & Co. KG - DE', 'Sponsor': 'N/A', 'Location': 'C2-6 ', 'Pavilion': '5', 'Hall Number': 'Hall 2', 'Country': 'Germany', 'Company Type': 'Manufacturer'},
    {'Name': 'ZUBAIR ENTERPRISES', 'Sponsor': 'N/A', 'Location': 'Z6-G18 ', 'Pavilion': '15', 'Hall Number': "Za'abeel Hall 6", 'Country': 'Pakistan', 'Company Type': 'N/A'},
    {'Name': 'Zwanenberg Food Group B.V.', 'Sponsor': 'N/A', 'Location': 'D3-12 ', 'Pavilion': '15', 'Hall Number': 'Hall 3', 'Country': 'Netherlands', 'Company Type': 'Manufacturer'}
]
# Create a DataFrame
df = pd.DataFrame(data)

# Save to Excel
df.to_excel('company_data5.xlsx', index=False)